"""phase20_topology_columns

Revision ID: 81e9864e53a7
Revises: a1f3d9e42c05
Create Date: 2026-04-20 01:25:07.681525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e9864e53a7'
down_revision: Union[str, None] = 'a1f3d9e42c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('site_topology', sa.String(length=32), nullable=True))
    op.add_column('scans', sa.Column('templates_found', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('urls_discovered', sa.Integer(), nullable=True))
    op.alter_column('scans', 'scraped_pages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'scraped_pages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('scans', 'urls_discovered')
    op.drop_column('scans', 'templates_found')
    op.drop_column('scans', 'site_topology')
    # ### end Alembic commands ###
