"""initial_schema

Revision ID: cdc14274a3f6
Revises: 
Create Date: 2026-04-14 13:32:23.499068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc14274a3f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('scan_mode', sa.String(length=32), nullable=False),
    sa.Column('site_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pages_audited', sa.Integer(), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('degraded_mode', sa.Boolean(), nullable=False),
    sa.Column('enrichment_status', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cache_meta',
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('misses', sa.Integer(), nullable=False),
    sa.Column('writes', sa.Integer(), nullable=False),
    sa.Column('last_reset', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tier')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('degraded_mode', sa.Boolean(), nullable=False),
    sa.Column('engine_timings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('scan_mode', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.Column('critical_issues', sa.Integer(), nullable=False),
    sa.Column('serious_issues', sa.Integer(), nullable=False),
    sa.Column('moderate_issues', sa.Integer(), nullable=False),
    sa.Column('minor_issues', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('priority_ranking', sa.JSON(), nullable=False),
    sa.Column('trust', sa.JSON(), nullable=False),
    sa.Column('engines_used', sa.JSON(), nullable=False),
    sa.Column('scan_time_seconds', sa.Float(), nullable=False),
    sa.Column('degraded_mode', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.Column('skipped_components', sa.JSON(), nullable=False),
    sa.Column('degradation_reason', sa.Text(), nullable=True),
    sa.Column('enrichment_status', sa.String(length=32), nullable=False),
    sa.Column('cognitive_scores', sa.JSON(), nullable=True),
    sa.Column('markdown_report', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_completed_at'), 'scans', ['completed_at'], unique=False)
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index('ix_scans_project_scan', 'scans', ['project_id', 'id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('wcag_criterion', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('affected_pages', sa.Integer(), nullable=False),
    sa.Column('enrichment_source', sa.String(length=64), nullable=False),
    sa.Column('fix', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrichments')
    op.drop_table('issues')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index('ix_scans_project_scan', table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_index(op.f('ix_scans_completed_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('pages')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('cache_meta')
    op.drop_table('audits')
    # ### end Alembic commands ###
